config/routes.rb
Rails.application.routes.draw do
  resources :books
  root 'books#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, :author, :status, :borrowed_at, :returned_at, presence: true
    enum status: [:prestado, :en_estante]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :set_book, only: [:show, :edit, :update, :destroy]
    
    def index
        @q = Book.ransack(params[:q])
        @books = @q.result(distinct: :true)
    end

    def show
    end

    def new
        @book = Book.new 
        @statuses = Book.statuses.keys.to_a 
    end 

    def create
        @book = Book.new(book_params)
        respond_to do |f|
            if @book.save
                f.html {redirect_to root_path, notice: 'Fue creado con éxito'}
            else
                f.html {render root_path, notice: 'No se pudo crear el libro'}
            end
        end
    end 

    def edit 
        @statuses = Book.statuses.keys.to_a 
    end 

    def update
        respond_to do |f|
            if @book.update(book_params)
                f.html {redirect_to root_path, notice: 'lo cambiaste exitosamente'}
            else 
                f.html {redirect_to edit_book_path}  #la diferencia con render es que este llama a una version más liviana de la vista, pero no redirige.
            end
        end 
    end 

    def destroy 
        @book.destroy
        respond_to do |f|
            f.html {redirect_to root_path, notice: 'F for the book'}
        end
    end

    private 
    def book_params 
        params.require(:book).permit(:title, :author, :status, :borrowed_at, :returned_at)
    end 

     def set_book 
        @book = Book.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
    <%= f.label :title, 'Title' %>
    <%= f.text_field :title %>

    <%= f.label :author, 'Author' %>
    <%= f.text_field :author %>

    <%= f.label :status, 'Estado' %>
    <%= f.select :status, @statuses %>

    <%= f.label :borrowed_at, 'Borrowed at' %>
    <%= f.datetime_select :borrowed_at %>

    <%= f.label :returned_at, 'Returned at' %>
    <%= f.datetime_select :returned_at %>

    <%= f.submit %>
<% end %>

app/views/books/edit.html.erb
<h1>Editar libro</h1>

<%= render 'form' %>

<%= link_to 'Back to the Index', root_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<%= search_form_for @q do |f| %>
    <%= f.label :status_eq, "Status" %> <!-- eq es el parámetro que recibirá ransack-->
    <%= f.select :status_eq, options_for_select(Book.statuses, @q.status_eq), {} %>
    <%= f.submit %>
<% end %> 

<table>
    <thead>
        <tr>
            <th><%= sort_link(@q, :title) %></th>
            <th><strong>Author</strong></th>
            <th><strong>Status</strong></th>
            <th><strong>Borrowed at</strong></th>
            <th><strong>Returned at</strong></th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
        <% @books.each do |b| %>
        <tr>
            <td> <%= b.title %></td>
            <td><%= b.author %></td>
            <td><%= b.status %></td>
            <td><%= b.borrowed_at %></td>
            <td><%= b.returned_at %></td>
            <td><%= link_to 'Show', b %></td>
            <td><%= link_to 'Edit', edit_book_path(b)%></td>
            <td><%= link_to 'Destroy', b, method: :delete, data: {confirm: '¿Seguro?'}%></td>
        </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'Add another book', new_book_path %>

app/views/books/new.html.erb
<h1>Add a Book!</h1>

<%= render 'form' %>

<%= link_to 'Return to Index', root_path %> 

app/views/books/show.html.erb
<p>
    <strong>Title</strong>
    <%= @book.title %>
</p>
<p>
    <strong>Author</strong>
    <%= @book.author %>
</p>
<p>
    <strong>
        Status
    </strong>
    <%= @book.status %>
</p>
<p>
    <strong>
        Borrowed at
    </strong>
    <%= @book.borrowed_at %>
</p>
<p>
    <strong>
        Returned at
    </strong>
    <%= @book.returned_at %>
</p>

<%= link_to 'Back to the Index', root_path %>

<%= link_to 'Edit this Book', edit_book_path(@book) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiBiblioteca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>